### ISSUE TITLE
New Feature: Add widget(s) on a given position

### ISSUE THREAD

**Issue by rlazom** [zesage/panorama#12]
Hi, first of all, I really love your plugin men, awesome job 😎🤘

I like to suggest a new feature, I think it could be very useful.
Feature: Add widget(s) on a given position.

The idea could be add to the current panorama class a list of objets(a widget with the position in the scene):
```
Panorama(
  child: Image.asset('assets/panorama.jpg'),
  widgets: <PositionedWidget>[]
),
```

And the PositionedWidget Class something like:
```
PositionedWidget {
  Vector3 position,
  Widget widget
}
```

This could be used to add (for example):
- A button in a position of the image an enable new interactions
- A text/hint when the user click a widget.
- Etc.

**Comment by dariocavada** [comment]
It would be great, because it could be used for virtual tours (click to an icon --> moving from one panorama to another) or to display information on a specific point (for example an object in a museum) etc ...

Would be good to have also an example of how to do this (also without changing the plugin)

**Comment by zesage** [comment]
791473c5c5e0a34d917e0972673668724b7c245b support add widgets

**Comment by dariocavada** [comment]
Some tests I've done:
- Panorama version `^0.1.2` does not have widgets support (just tried, but no new code for widgets)
- Taking the `791473c` version and the example in the repository I have some strange errors
- If I use a simple widget like this: 
``` dart
Hotspot(
  latitude: -76.0,
  longitude: -52.0,
  widget: GestureDetector(
    onTap: () {
      print('tap tap');
    },
    child: Container(
      //padding: EdgeInsets.all(8),
      color: Colors.white,
      child: Icon(Icons.search),
    ),
  ),
),
```

it works (at least on Android):

![pano-widgets-test](https://user-images.githubusercontent.com/4304176/103017628-2ec9c580-4544-11eb-97fb-6c7dad345e09.jpg)

**Comment by rlazom** [comment]
Awesome job @zesage. I love it.

**Comment by rlazom** [comment]
Tested and working
