### ISSUE TITLE
Feature request: cropped area parameters

### ISSUE THREAD

**Issue by deckerst** [zesage/panorama#14]
This package is great, but panorama images that do not cover the full 360/180 are stretched.

This happens when the panorama is cropped, for example with the `CroppedAreaLeftPixels` and `CroppedAreaTopPixels` from the Google panorama spec: https://developers.google.com/streetview/spherical-metadata

It would be nice if the Panorama constructor provided parameters to specify the cropped area.

When the image does not cover the full 360/180, some apps just render a black background, some apps do something fancier (for example Google Photos interpolates the pixels from the edge of the image to fill the background). Personally I would be happy with a plain black background, but it can be something fun to explore.

**Comment by zesage** [comment]
52d70a0e071e148f3f3954a59ed74a5696d3bfa2 add cropped area

**Comment by deckerst** [comment]
Works like a charm, thank you!
