### ISSUE TITLE
rotation with phone(like faceobok 360 photo)

### ISSUE THREAD

**Issue by FahriBilici** [zesage/panorama#20]
can we rotate picture by rotating phone like facebook 360 photos?

**Comment by rlazom** [comment]
Yes

**Comment by FahriBilici** [comment]
> Yes

How?

**Comment by rlazom** [comment]
> > Yes
> 
> How?

Please check the documentation and the example app folder.

Panorama(
...
   sensorControl: SensorControl.Orientation,
...
)
