### ISSUE TITLE
flutter 3.10 not support ios 

### ISSUE THREAD

**Issue by feeza10250** [zesage/panorama#50]
not show image black screen

<img width="451" alt="Screenshot 2566-05-11 at 18 49 00" src="https://github.com/zesage/panorama/assets/20635185/564d4dbd-c491-4456-8b12-63d62731acf6">

IOS-> not support
Android -> support

- [x] **Fixed with downgrade Flutter version 3.7.12**

_______________________________________________________________________________________
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-TH)
    • Flutter version 3.10.0 on channel stable at /Users/?????????/Desktop/????????/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/???????/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/??????/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by Limatationz** [comment]
Another option is to add this to your `Info.plist` when you want to use 3.10.0 (disables Impeller):

```
<key>FLTEnableImpeller</key>
<false />
```

[Source](https://docs.flutter.dev/perf/impeller#ios)

**Comment by JohnWeidner** [comment]
Disabling impeller as Limatationz suggested fixed this for me. Maybe this is caused by one of these impeller issues:
[127705](https://github.com/flutter/flutter/issues/127705)
[127486](https://github.com/flutter/flutter/issues/127486)
